import { css } from "@/styles";
export const topBarStyles = css({
  position: "sticky",
  top: 0,
  zIndex: 20,
  borderBottom: "1px solid $colors$border",
  backgroundColor: "$background",
  fontFamily: "$sans",
  ".topbar-inner": {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    width: "100%",
    maxWidth: 1280,
    height: 64,
    margin: "0 auto",
    padding: "0 24px",
  },
  ".topbar-left": {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  ".topbar-actions": {
    position: "relative",
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  ".topbar-toggle": {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 36,
    height: 36,
    border: 0,
    borderRadius: "$md",
    background: "transparent",
    color: "$textSecondary",
  },
  ".topbar-toggle:hover": { background: "$backgroundSecondary" },
  ".topbar-nav": { display: "none" },
  ".nav-list": {
    display: "flex",
    gap: 4,
    padding: 0,
    margin: 0,
    listStyle: "none",
  },
  ".nav-vertical": { flexDirection: "column" },
  ".nav-link": {
    display: "block",
    padding: "8px 10px",
    fontSize: "var(--fontSizes-size13)",
    fontWeight: 500,
    borderRadius: "$md",
    color: "$textSecondary",
    whiteSpace: "nowrap",
    textDecoration: "none",
  },
  ".nav-link:hover": { color: "$primary" },
  ".nav-link-active": {
    background: "$adoptedBackground",
    color: "$primary",
    fontWeight: 600,
  },
  ".topbar-dropdown": {
    position: "absolute",
    top: "calc(100% + 8px)",
    right: 0,
    minWidth: 150,
    padding: 4,
    border: "1px solid $colors$border",
    borderRadius: "$lg",
    background: "$background",
    boxShadow: "$md",
  },
  ".topbar-dropdown-item": {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "10px 12px",
    border: 0,
    borderRadius: "$md",
    background: "transparent",
    color: "$negative",
    fontSize: "var(--fontSizes-size13)",
    textAlign: "left",
  },
  ".topbar-dropdown-item:hover": { background: "$negativeBackground" },
  ".topbar-organizer": { display: "none" },
  ".topbar-mobile": {
    padding: "8px 16px 16px",
    borderTop: "1px solid $colors$border",
    background: "$background",
    boxShadow: "$md",
  },
  "button:focus-visible, a:focus-visible": {
    outline: "2px solid $colors$primaryLight",
    outlineOffset: 3,
  },
  "@sm": { ".topbar-organizer": { display: "block" } },
  "@media (min-width: 1050px)": {
    ".topbar-nav": { display: "block" },
    ".topbar-toggle, .topbar-mobile": { display: "none" },
  },
  "@media (max-width: 639px)": { ".topbar-inner": { padding: "0 16px" } },
});
